spring:
  application:
    name: cart-service

  datasource:
    url: ${CART_DB_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka