spring:
  application:
    name: sale-service

  datasource:
    url: ${SALE_DB_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

  health:
    circuitbreaker:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      sale-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        ignore-exceptions:
          - com.nicodev.sale_service.exception.NotFoundException
          - com.nicodev.sale_service.exception.BadRequestException